# Generated by Django 3.1.2 on 2020-10-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('tlf', models.CharField(max_length=10)),
                ('colegio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('tlf', models.CharField(max_length=10)),
                ('colegio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsleep', models.IntegerField()),
                ('animo', models.CharField(max_length=15)),
                ('ejercicio', models.BooleanField()),
                ('minEjercicio', models.IntegerField()),
                ('FechaEjecicio', models.DateField()),
            ],
        ),
    ]
